# Generated by Django 4.2.7 on 2023-12-01 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.ImageField(default='avatar.png', upload_to='midia', verbose_name='Imagem da moto')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo da moto')),
                ('marca', models.CharField(choices=[('Bimota', 'Bimota'), ('Dafra', 'Dafra'), ('Suzuki', 'Suzuki'), ('BMW', 'BMW'), ('Kawasaki', 'Kawasaki'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Yamaha', 'Yamaha'), ('Ducati', 'Ducati'), ('Honda', 'Honda')], default='Nenhuma_dessas_marca', max_length=20)),
                ('condicao', models.CharField(choices=[('SemiNovos', 'Semi Novo'), ('Novos', 'Novo'), ('Usados', 'Usado')], default='Novos', max_length=20)),
                ('precoo', models.CharField(choices=[('LowToHigh', 'Abaixo de 30k'), ('HighToLow', 'Acima de 30k')], default='Abaixo de 30k', max_length=20)),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição da moto')),
                ('preco', models.CharField(max_length=20, verbose_name='Preço do carro')),
                ('data', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=50)),
                ('km', models.CharField(max_length=100, verbose_name='Quilometros')),
                ('troca', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Aceita Troca')),
                ('Refrigeracao', models.CharField(choices=[('ar', 'Ar'), ('líquido', 'líquido')], default='Líquido', max_length=20, verbose_name='Refrigeração')),
                ('cor', models.CharField(max_length=20)),
                ('ipva', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=10)),
                ('Partida', models.CharField(choices=[('pedal', 'Pedal'), ('elétrica', 'Elétrica')], default='Pedal', max_length=30)),
                ('Cilindrada', models.IntegerField()),
                ('marchas', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.ImageField(default='avatar.png', upload_to='midia', verbose_name='Imagem do carro')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo do carro')),
                ('marca', models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Ford', 'Ford'), ('Peugeot', 'Peugeot'), ('Lamborghini', 'Lamborghini'), ('Tesla', 'Tesla'), ('Ferrari', 'Ferrari'), ('Volkswagen', 'Volkswagen'), ('Porsche', 'Porsche')], default='Nenhuma_dessas_marca', max_length=20)),
                ('condicao', models.CharField(choices=[('SemiNovos', 'Semi Novo'), ('Novos', 'Novo'), ('Usados', 'Usado')], default='Novos', max_length=20)),
                ('precoo', models.CharField(choices=[('LowToHigh', 'Abaixo de 100k'), ('HighToLow', 'Acima de 100k')], default='Abaixo de 100k', max_length=20)),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição do carro')),
                ('preco', models.CharField(max_length=20, verbose_name='Preço do carro')),
                ('data', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=50)),
                ('km', models.CharField(max_length=100, verbose_name='Quilometros')),
                ('troca', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Aceita Troca')),
                ('combustivel', models.CharField(max_length=30)),
                ('cambio', models.CharField(choices=[('Automatico', 'Automatico'), ('Manual', 'Manual')], default='Manual', max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('ipva', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
