# Generated by Django 4.2.7 on 2023-12-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Usados', 'Usado'), ('SemiNovos', 'Semi Novo'), ('Novos', 'Novo')], default='Novos', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ipva',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Volkswagen', 'Volkswagen'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Porsche', 'Porsche'), ('Tesla', 'Tesla'), ('Lamborghini', 'Lamborghini'), ('Peugeot', 'Peugeot'), ('Nenhuma_dessas_marca', 'Nenhuma dessas')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='troca',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='Partida',
            field=models.CharField(choices=[('elétrica', 'Elétrica'), ('pedal', 'Pedal')], default='Pedal', max_length=30),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='condicao',
            field=models.CharField(choices=[('Usados', 'Usado'), ('SemiNovos', 'Semi Novo'), ('Novos', 'Novo')], default='Novos', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='ipva',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='marca',
            field=models.CharField(choices=[('Bimota', 'Bimota'), ('Suzuki', 'Suzuki'), ('BMW', 'BMW'), ('Yamaha', 'Yamaha'), ('Honda', 'Honda'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Dafra', 'Dafra'), ('Ducati', 'Ducati'), ('Kawasaki', 'Kawasaki')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='precoo',
            field=models.CharField(choices=[('HighToLow', 'Acima de 30k'), ('LowToHigh', 'Abaixo de 30k')], default='Abaixo de 30k', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='troca',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
    ]
