# Generated by Django 4.2.7 on 2023-12-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_anuncio_cambio_alter_anuncio_condicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='cambio',
            field=models.CharField(choices=[('Automatico', 'Automatico'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ipva',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Lamborghini', 'Lamborghini'), ('Ferrari', 'Ferrari'), ('Tesla', 'Tesla'), ('Porsche', 'Porsche'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Ford', 'Ford'), ('Peugeot', 'Peugeot'), ('Volkswagen', 'Volkswagen')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='troca',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='Partida',
            field=models.CharField(choices=[('elétrica', 'Elétrica'), ('pedal', 'Pedal')], default='Pedal', max_length=30),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='ipva',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='marca',
            field=models.CharField(choices=[('Yamaha', 'Yamaha'), ('BMW', 'BMW'), ('Ducati', 'Ducati'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Kawasaki', 'Kawasaki'), ('Bimota', 'Bimota'), ('Dafra', 'Dafra'), ('Suzuki', 'Suzuki'), ('Honda', 'Honda')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='troca',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
    ]
