# Generated by Django 4.2.7 on 2023-12-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_anuncio_cambio_alter_anuncio_ipva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='cambio',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automatico')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('Usados', 'Usado'), ('Novos', 'Novo'), ('SemiNovos', 'Semi Novo')], default='Novos', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ipva',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Lamborghini', 'Lamborghini'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precoo',
            field=models.CharField(choices=[('LowToHigh', 'Abaixo de 100k'), ('HighToLow', 'Acima de 100k')], default='Abaixo de 100k', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='troca',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='Partida',
            field=models.CharField(choices=[('pedal', 'Pedal'), ('elétrica', 'Elétrica')], default='Pedal', max_length=30),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='Refrigeracao',
            field=models.CharField(choices=[('líquido', 'líquido'), ('ar', 'Ar')], default='Líquido', max_length=20, verbose_name='Refrigeração'),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='condicao',
            field=models.CharField(choices=[('Usados', 'Usado'), ('Novos', 'Novo'), ('SemiNovos', 'Semi Novo')], default='Novos', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='ipva',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='marca',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Dafra', 'Dafra'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Kawasaki', 'Kawasaki'), ('Yamaha', 'Yamaha'), ('Suzuki', 'Suzuki'), ('BMW', 'BMW'), ('Bimota', 'Bimota'), ('Ducati', 'Ducati')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='precoo',
            field=models.CharField(choices=[('HighToLow', 'Acima de 30k'), ('LowToHigh', 'Abaixo de 30k')], default='Abaixo de 30k', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='troca',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
    ]
