# Generated by Django 4.2.7 on 2023-12-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_alter_anuncio_condicao_alter_anuncio_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='cambio',
            field=models.CharField(choices=[('Automatico', 'Automatico'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='condicao',
            field=models.CharField(choices=[('SemiNovos', 'Semi Novo'), ('Novos', 'Novo'), ('Usados', 'Usado')], default='Novos', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ipva',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Tesla', 'Tesla'), ('Porsche', 'Porsche'), ('Volkswagen', 'Volkswagen'), ('Peugeot', 'Peugeot'), ('Chevrolet', 'Chevrolet')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precoo',
            field=models.CharField(choices=[('LowToHigh', 'Abaixo de 100k'), ('HighToLow', 'Acima de 100k')], default='Abaixo de 100k', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='troca',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='Partida',
            field=models.CharField(choices=[('pedal', 'Pedal'), ('elétrica', 'Elétrica')], default='Pedal', max_length=30),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='condicao',
            field=models.CharField(choices=[('SemiNovos', 'Semi Novo'), ('Novos', 'Novo'), ('Usados', 'Usado')], default='Novos', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='ipva',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='marca',
            field=models.CharField(choices=[('Dafra', 'Dafra'), ('BMW', 'BMW'), ('Kawasaki', 'Kawasaki'), ('Yamaha', 'Yamaha'), ('Ducati', 'Ducati'), ('Nenhuma_dessas_marca', 'Nenhuma dessas'), ('Suzuki', 'Suzuki'), ('Bimota', 'Bimota'), ('Honda', 'Honda')], default='Nenhuma_dessas_marca', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='precoo',
            field=models.CharField(choices=[('HighToLow', 'Acima de 30k'), ('LowToHigh', 'Abaixo de 30k')], default='Abaixo de 30k', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunciomoto',
            name='troca',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=10, verbose_name='Aceita Troca'),
        ),
    ]
