# Generated by Django 4.2.7 on 2023-12-01 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemPerfil', models.ImageField(default='avatar.png', upload_to='midia', verbose_name='Imagem do perfil')),
                ('dataa', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('estado', models.CharField(max_length=40, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('cpf', models.CharField(max_length=15, null=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
